### ISSUE TITLE
croswalk_affiliations fails with empty affiliations

### ISSUE THREAD

**Issue by mconlon17** [gwu-libraries/orcid2vivo#20]
```
/usr/bin/python /Users/mikeconlon/PycharmProjects/orcid2vivo/orcid2vivo.py 0000-0002-1304-8447
Traceback (most recent call last):
  File "/Users/mikeconlon/PycharmProjects/orcid2vivo/orcid2vivo.py", line 82, in <module>
    skip_person=args.skip_person, namespace=args.namespace)
  File "/Users/mikeconlon/PycharmProjects/orcid2vivo/orcid2vivo.py", line 39, in crosswalk
    crosswalk_affiliations(orcid_profile, person_uri, graph)
  File "/Users/mikeconlon/PycharmProjects/orcid2vivo/app/affiliations.py", line 12, in     crosswalk_affiliations
    for affiliation in (orcid_profile["orcid-profile"].get("orcid-activities") or {}).get("affiliations", {})\
AttributeError: 'NoneType' object has no attribute 'get'

Process finished with exit code 1
```

**Comment by justinlittman** [comment]
closed by #21
